org: alejomendoza
app: sq-e2e-tests
service: sq-e2e-tests

plugins:
  - serverless-webpack
  - serverless-offline

package:
  exclude:
    - node_modules/**

provider:
  name: aws
  apiGateway:
    shouldStartNameWithService: true
    binaryMediaTypes:
      - '*/*'
  runtime: nodejs14.x
  region: us-west-1

functions:
  hello:
    handler: src/handler.default
    timeout: 100
    events:
      - http:
          method: get
          path: test
    environment:
      NODE_PATH: './:/opt/nodejs/node_modules'
    layers:
      - arn:aws:lambda:us-west-1:764866452798:layer:chrome-aws-lambda:24
      - arn:aws:lambda:us-west-1:389502703865:layer:jest-layer-package:1

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'npm'
