org: jesmarsc
app: sq-e2e-tests
service: sq-e2e-tests

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-deployment-bucket
  - serverless-layers

package:
  exclude:
    - node_modules/**

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-1
  memorySize: 2048
  timeout: 30
  apiGateway:
    shouldStartNameWithService: true
  deploymentBucket:
    name: jest-bucket

functions:
  tests:
    handler: src/handler.default
    events:
      - http:
          method: get
          path: test
    environment:
      NODE_PATH: './:/opt/nodejs/node_modules'

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'npm'
  serverless-layers:
    - common:
        dependenciesPath: ./package.json
    - staticArn:
        arn: arn:aws:lambda:us-west-1:764866452798:layer:chrome-aws-lambda:25
